### ISSUE TITLE
Suggestion: hi-res icon

### ISSUE THREAD

**Issue by rsn8887** [p-sam/supermariowar-nx#2]
I made an alternative new icon. It is a bit ugly, but hi-res ;) Decide for yourself which one you like more. I personally prefer "hi-res" icons like this, but it is a matter of taste. 

Here is my icon suggestion:
![](https://i.postimg.cc/Xq7cfrq3/icon0.jpg)

**Comment by p-sam** [comment]
Thanks for the icon suggestion! I appreciate it, I see people have started making custom icons for the game on twitter and gbatemp. Not just a matter of taste, I prefer to have the original icon from the main repo, I just edited a bit so it fits the 256x256 dimensions.

**Comment by rsn8887** [comment]
Understood!
