### ISSUE TITLE
Single joycon mode

### ISSUE THREAD

**Issue by rsn8887** [p-sam/supermariowar-nx#3]
I made a PR here to implement single joy con mode, and that linear gfx filter I mentioned in the issues:
https://github.com/p-sam/supermariowar/pull/1

I cannot test it at the moment, I don't have my Switch, but it should work.

Feel free to use or ignore, just trying to help :)

**Comment by p-sam** [comment]
Thanks for that too, it's definitely a very needed feature. as with your other issue, I'll discuss code related matters directly into the subrepo PR. Please rename the issue into "Single joycon mode" or "Split JoyCon mode", I'll close it once it's implemented.

**Comment by rsn8887** [comment]
Implemented with https://github.com/p-sam/supermariowar/commit/0d1810eaa8e6c90613c3e12f5099f0762c3772e9
